### ISSUE TITLE
Same DataType for different formats

### ISSUE THREAD

**Issue by hacki11** [fredlcore/BSB-LAN#358] opened 2021-03-23 22:07 UTC
Hi,
i found different formats for the same datatype 5

I need to parse the user input and convert it to be able to set it over the api.

"23.03.2021 23:03:28" conversion to "23.03.2021_23:03:28" is needed.
"1. 04:00 - 21:00 2. --:-- - --:-- 3. --:-- - --:--" => 04:00-21:00_xx:xx-xx:xx_xx:xx-xx:xx" is needed.

Because they are listed as the same datatype in can not distinguish between. 
![image](https://user-images.githubusercontent.com/15319906/112224799-1d1fb900-8c2c-11eb-8cba-4cc9accfbdb4.png)

**Comment by fredlcore** [comment] 2021-03-23 22:14
Duplicate of #250

**Closed by fredlcore** 2021-03-23 22:14 UTC
